rework api (#3)
* start work on api design

* some more changes

* some more changes

* move queue traits to lib.rs

* add more docs and some formatting

* some fmt + featre

* add safety comments + some changes

* set correct default features

* fix some errs and change ci

* fix some errs and change namings

diff --git a/.github/workflows/nostd.yml b/.github/workflows/nostd.yml
--- a/.github/workflows/nostd.yml
+++ b/.github/workflows/nostd.yml
@@ -12,12 +12,12 @@ concurrency:
   cancel-in-progress: true
 name: no-std
 jobs:
-  nostd:
+  nostd_pass:
     runs-on: ubuntu-latest
     name: ${{ matrix.target }}
     strategy:
       matrix:
-        target: [thumbv7m-none-eabi, aarch64-unknown-none]
+        target: [aarch64-unknown-none]
     steps:
       - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
         with:
@@ -30,3 +30,35 @@ jobs:
         run: rustup target add ${{ matrix.target }}
       - name: cargo check
         run: cargo check --target ${{ matrix.target }} --no-default-features
+  nostd_fail:
+    runs-on: ubuntu-latest
+    name: ${{ matrix.target }}
+    strategy:
+      matrix:
+        target: [thumbv7m-none-eabi]
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
+        with:
+          submodules: true
+      - name: Install stable
+        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
+        with:
+          toolchain: stable
+      - name: rustup target add ${{ matrix.target }}
+        run: rustup target add ${{ matrix.target }}
+      - name: cargo check
+        run: cargo check --target ${{ matrix.target }} --no-default-features
+        # currently there is no support for this without feature atomic-fallback
+        continue-on-error: true
+        id: check_result
+      - name: verify
+        run: |
+          if [ "${{ steps.check_result.outcome }}" = "failure" ]; then
+            echo "mission failed succesfully"
+            exit 0
+          else
+            echo "no compile err"
+            exit 1
+          fi
+      - name: correct
+        run: cargo check --target ${{ matrix.target }} --no-default-features --features atomic-fallback
